version: "3.3"

services:
  fdb:
    build:
      context: .
      dockerfile: ./fdb/db.Dockerfile
    ports:
      - 4500:4500
    environment:
      - HOST_IP=0.0.0.0
  client:
    build:
      context: .
      dockerfile: ./fdb/client.Dockerfile
    depends_on:
      - fdb
    ports:
      - 8090:8090
    environment:
      - FDBHOSTNAME=fdb
    volumes:
      - ./vinyl:/opt/app
      - ivycache:/root/.ivy2/cache

volumes:
  ivycache: {}
