version: "3.3"

services:
  db:
    build:
      context: .
      dockerfile: ./db/db.Dockerfile
    ports:
      - 4500:4500
    environment:
      - HOST_IP=0.0.0.0
  client:
    build:
      context: .
      dockerfile: ./db/client.Dockerfile
    depends_on:
      - db
    ports:
      - 8090:8090
    environment:
      - FDBHOSTNAME=db
    volumes:
      - ./app:/opt/app
      - ivycache:/root/.ivy2/cache

volumes:
  ivycache: {}
