// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package vinyl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Query struct {
	Username             string    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Keyspace             string    `protobuf:"bytes,3,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	FileDescriptor       []byte    `protobuf:"bytes,4,opt,name=file_descriptor,json=fileDescriptor,proto3" json:"file_descriptor,omitempty"`
	Tables               []*Table  `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty"`
	Insertions           []*Insert `protobuf:"bytes,6,rep,name=insertions,proto3" json:"insertions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Query) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Query) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *Query) GetFileDescriptor() []byte {
	if m != nil {
		return m.FileDescriptor
	}
	return nil
}

func (m *Query) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *Query) GetInsertions() []*Insert {
	if m != nil {
		return m.Insertions
	}
	return nil
}

type Insert struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insert) Reset()         { *m = Insert{} }
func (m *Insert) String() string { return proto.CompactTextString(m) }
func (*Insert) ProtoMessage()    {}
func (*Insert) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Insert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insert.Unmarshal(m, b)
}
func (m *Insert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insert.Marshal(b, m, deterministic)
}
func (m *Insert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insert.Merge(m, src)
}
func (m *Insert) XXX_Size() int {
	return xxx_messageInfo_Insert.Size(m)
}
func (m *Insert) XXX_DiscardUnknown() {
	xxx_messageInfo_Insert.DiscardUnknown(m)
}

var xxx_messageInfo_Insert proto.InternalMessageInfo

func (m *Insert) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Insert) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Table struct {
	FieldOptions         map[string]*FieldOptions `protobuf:"bytes,1,rep,name=field_options,json=fieldOptions,proto3" json:"field_options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name                 string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetFieldOptions() map[string]*FieldOptions {
	if m != nil {
		return m.FieldOptions
	}
	return nil
}

func (m *Table) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// from record_metadata_options.proto
type FieldOptions struct {
	PrimaryKey           bool                      `protobuf:"varint,2,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Index                *FieldOptions_IndexOption `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetPrimaryKey() bool {
	if m != nil {
		return m.PrimaryKey
	}
	return false
}

func (m *FieldOptions) GetIndex() *FieldOptions_IndexOption {
	if m != nil {
		return m.Index
	}
	return nil
}

type FieldOptions_IndexOption struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Unique               bool     `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions_IndexOption) Reset()         { *m = FieldOptions_IndexOption{} }
func (m *FieldOptions_IndexOption) String() string { return proto.CompactTextString(m) }
func (*FieldOptions_IndexOption) ProtoMessage()    {}
func (*FieldOptions_IndexOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3, 0}
}

func (m *FieldOptions_IndexOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions_IndexOption.Unmarshal(m, b)
}
func (m *FieldOptions_IndexOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions_IndexOption.Marshal(b, m, deterministic)
}
func (m *FieldOptions_IndexOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions_IndexOption.Merge(m, src)
}
func (m *FieldOptions_IndexOption) XXX_Size() int {
	return xxx_messageInfo_FieldOptions_IndexOption.Size(m)
}
func (m *FieldOptions_IndexOption) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions_IndexOption.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions_IndexOption proto.InternalMessageInfo

func (m *FieldOptions_IndexOption) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FieldOptions_IndexOption) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func init() {
	proto.RegisterType((*Query)(nil), "vinyl.Query")
	proto.RegisterType((*Insert)(nil), "vinyl.Insert")
	proto.RegisterType((*Table)(nil), "vinyl.Table")
	proto.RegisterMapType((map[string]*FieldOptions)(nil), "vinyl.Table.FieldOptionsEntry")
	proto.RegisterType((*FieldOptions)(nil), "vinyl.FieldOptions")
	proto.RegisterType((*FieldOptions_IndexOption)(nil), "vinyl.FieldOptions.IndexOption")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x6a, 0xe3, 0x30,
	0x10, 0x46, 0x49, 0x6c, 0xb2, 0x63, 0x27, 0xbb, 0xab, 0x5d, 0x16, 0x93, 0xc3, 0x26, 0x98, 0x42,
	0xd3, 0x43, 0x7d, 0x70, 0x29, 0xb4, 0xbd, 0xf6, 0x07, 0x42, 0x0f, 0xa5, 0x22, 0xf7, 0xa0, 0xc4,
	0x4a, 0x11, 0x71, 0x6c, 0x57, 0xb2, 0xd3, 0xea, 0x71, 0xfa, 0x12, 0x7d, 0x97, 0xbe, 0x4d, 0xd1,
	0x4f, 0x82, 0xa1, 0xbd, 0xcd, 0xf7, 0xa3, 0xf9, 0x66, 0xc6, 0x86, 0xe1, 0x96, 0x49, 0x49, 0x9f,
	0x98, 0x4c, 0x2a, 0x51, 0xd6, 0x25, 0xf6, 0x76, 0xbc, 0x50, 0x79, 0xfc, 0x81, 0xc0, 0x7b, 0x6c,
	0x98, 0x50, 0x78, 0x04, 0xfd, 0x46, 0x32, 0x51, 0xd0, 0x2d, 0x8b, 0xd0, 0x04, 0x4d, 0x7f, 0x90,
	0x03, 0xd6, 0x5a, 0x45, 0xa5, 0x7c, 0x29, 0x45, 0x16, 0x75, 0xac, 0xb6, 0xc7, 0x5a, 0xdb, 0x30,
	0x25, 0x2b, 0xba, 0x62, 0x51, 0xd7, 0x6a, 0x7b, 0x8c, 0x8f, 0xe1, 0xe7, 0x9a, 0xe7, 0x6c, 0x91,
	0x31, 0xb9, 0x12, 0xbc, 0xaa, 0x4b, 0x11, 0xf5, 0x26, 0x68, 0x1a, 0x92, 0xa1, 0xa6, 0x6f, 0x0e,
	0x2c, 0x3e, 0x02, 0xbf, 0xa6, 0xcb, 0x9c, 0xc9, 0xc8, 0x9b, 0x74, 0xa7, 0x41, 0x1a, 0x26, 0x66,
	0xbc, 0x64, 0xae, 0x49, 0xe2, 0x34, 0x7c, 0x0a, 0xc0, 0x0b, 0xc9, 0x44, 0xcd, 0xcb, 0x42, 0x46,
	0xbe, 0x71, 0x0e, 0x9c, 0x73, 0x66, 0x04, 0xd2, 0x32, 0xc4, 0x29, 0xf8, 0x96, 0xc5, 0x7f, 0xc1,
	0x33, 0x2d, 0xdc, 0x62, 0x16, 0x60, 0x0c, 0xbd, 0x8c, 0xd6, 0xd4, 0x6c, 0x14, 0x12, 0x53, 0xc7,
	0xef, 0x08, 0x3c, 0x13, 0x8a, 0xaf, 0x61, 0xb0, 0xe6, 0x2c, 0xcf, 0x16, 0x65, 0x65, 0xf3, 0x90,
	0xc9, 0xfb, 0xdf, 0x9e, 0x2c, 0xb9, 0xd3, 0x8e, 0x07, 0x6b, 0xb8, 0x2d, 0x6a, 0xa1, 0x48, 0xb8,
	0x6e, 0x51, 0x3a, 0xc2, 0x1c, 0xd4, 0x1e, 0xcd, 0xd4, 0xa3, 0x39, 0xfc, 0xfe, 0xf2, 0x0c, 0xff,
	0x82, 0xee, 0x86, 0x29, 0x37, 0x9f, 0x2e, 0xf1, 0x09, 0x78, 0x3b, 0x9a, 0x37, 0xf6, 0x6d, 0x90,
	0xfe, 0x71, 0xb9, 0xed, 0xa7, 0xc4, 0x3a, 0xae, 0x3a, 0x17, 0x28, 0x7e, 0x43, 0x10, 0xb6, 0x35,
	0x3c, 0x86, 0xa0, 0x12, 0x7c, 0x4b, 0x85, 0x5a, 0xe8, 0xce, 0xba, 0x4b, 0x9f, 0x80, 0xa3, 0xee,
	0x99, 0xc2, 0xe7, 0xe0, 0xf1, 0x22, 0x63, 0xaf, 0xe6, 0xab, 0x05, 0xe9, 0xf8, 0x9b, 0x80, 0x64,
	0xa6, 0x0d, 0x16, 0x10, 0xeb, 0x1e, 0x5d, 0x42, 0xd0, 0x62, 0xf5, 0x86, 0xb5, 0xaa, 0xf6, 0x97,
	0x35, 0x35, 0xfe, 0x07, 0x7e, 0x53, 0xf0, 0x67, 0x37, 0x7b, 0x9f, 0x38, 0xb4, 0xf4, 0xcd, 0xaf,
	0x77, 0xf6, 0x19, 0x00, 0x00, 0xff, 0xff, 0x36, 0x2e, 0x23, 0x8d, 0x8c, 0x02, 0x00, 0x00,
}
