// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transport.proto

package transport

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryComponent_ComponentType int32

const (
	QueryComponent_AND   QueryComponent_ComponentType = 0
	QueryComponent_OR    QueryComponent_ComponentType = 1
	QueryComponent_NOT   QueryComponent_ComponentType = 2
	QueryComponent_FIELD QueryComponent_ComponentType = 3
)

var QueryComponent_ComponentType_name = map[int32]string{
	0: "AND",
	1: "OR",
	2: "NOT",
	3: "FIELD",
}

var QueryComponent_ComponentType_value = map[string]int32{
	"AND":   0,
	"OR":    1,
	"NOT":   2,
	"FIELD": 3,
}

func (x QueryComponent_ComponentType) String() string {
	return proto.EnumName(QueryComponent_ComponentType_name, int32(x))
}

func (QueryComponent_ComponentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{2, 0}
}

type Field_ComponentType int32

const (
	Field_EQUALS       Field_ComponentType = 0
	Field_GREATER_THAN Field_ComponentType = 1
	Field_LESS_THAN    Field_ComponentType = 2
	Field_EMPTY        Field_ComponentType = 3
	Field_NOT_EMPTY    Field_ComponentType = 4
	Field_IS_NULL      Field_ComponentType = 5
	Field_MATCHES      Field_ComponentType = 6
)

var Field_ComponentType_name = map[int32]string{
	0: "EQUALS",
	1: "GREATER_THAN",
	2: "LESS_THAN",
	3: "EMPTY",
	4: "NOT_EMPTY",
	5: "IS_NULL",
	6: "MATCHES",
}

var Field_ComponentType_value = map[string]int32{
	"EQUALS":       0,
	"GREATER_THAN": 1,
	"LESS_THAN":    2,
	"EMPTY":        3,
	"NOT_EMPTY":    4,
	"IS_NULL":      5,
	"MATCHES":      6,
}

func (x Field_ComponentType) String() string {
	return proto.EnumName(Field_ComponentType_name, int32(x))
}

func (Field_ComponentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{3, 0}
}

type Value_ValueType int32

const (
	Value_DOUBLE Value_ValueType = 0
	Value_FLOAT  Value_ValueType = 1
	Value_INT32  Value_ValueType = 2
	Value_INT64  Value_ValueType = 3
	Value_SINT32 Value_ValueType = 5
	Value_SINT64 Value_ValueType = 6
	Value_BOOL   Value_ValueType = 9
	Value_STRING Value_ValueType = 10
	Value_BYTES  Value_ValueType = 11
)

var Value_ValueType_name = map[int32]string{
	0:  "DOUBLE",
	1:  "FLOAT",
	2:  "INT32",
	3:  "INT64",
	5:  "SINT32",
	6:  "SINT64",
	9:  "BOOL",
	10: "STRING",
	11: "BYTES",
}

var Value_ValueType_value = map[string]int32{
	"DOUBLE": 0,
	"FLOAT":  1,
	"INT32":  2,
	"INT64":  3,
	"SINT32": 5,
	"SINT64": 6,
	"BOOL":   9,
	"STRING": 10,
	"BYTES":  11,
}

func (x Value_ValueType) String() string {
	return proto.EnumName(Value_ValueType_name, int32(x))
}

func (Value_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{4, 0}
}

type Request struct {
	Username             string    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Keyspace             string    `protobuf:"bytes,3,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	FileDescriptor       []byte    `protobuf:"bytes,4,opt,name=file_descriptor,json=fileDescriptor,proto3" json:"file_descriptor,omitempty"`
	Tables               []*Table  `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty"`
	Insertions           []*Insert `protobuf:"bytes,6,rep,name=insertions,proto3" json:"insertions,omitempty"`
	Query                *Query    `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Request) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *Request) GetFileDescriptor() []byte {
	if m != nil {
		return m.FileDescriptor
	}
	return nil
}

func (m *Request) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *Request) GetInsertions() []*Insert {
	if m != nil {
		return m.Insertions
	}
	return nil
}

func (m *Request) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type Query struct {
	RecordType           string          `protobuf:"bytes,1,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Filter               *QueryComponent `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{1}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetRecordType() string {
	if m != nil {
		return m.RecordType
	}
	return ""
}

func (m *Query) GetFilter() *QueryComponent {
	if m != nil {
		return m.Filter
	}
	return nil
}

type QueryComponent struct {
	Child                *QueryComponent              `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	Children             []*QueryComponent            `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	ComponentType        QueryComponent_ComponentType `protobuf:"varint,3,opt,name=component_type,json=componentType,proto3,enum=vinyl.QueryComponent_ComponentType" json:"component_type,omitempty"`
	Not                  *QueryComponent              `protobuf:"bytes,4,opt,name=not,proto3" json:"not,omitempty"`
	Field                *Field                       `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *QueryComponent) Reset()         { *m = QueryComponent{} }
func (m *QueryComponent) String() string { return proto.CompactTextString(m) }
func (*QueryComponent) ProtoMessage()    {}
func (*QueryComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{2}
}

func (m *QueryComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryComponent.Unmarshal(m, b)
}
func (m *QueryComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryComponent.Marshal(b, m, deterministic)
}
func (m *QueryComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryComponent.Merge(m, src)
}
func (m *QueryComponent) XXX_Size() int {
	return xxx_messageInfo_QueryComponent.Size(m)
}
func (m *QueryComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryComponent.DiscardUnknown(m)
}

var xxx_messageInfo_QueryComponent proto.InternalMessageInfo

func (m *QueryComponent) GetChild() *QueryComponent {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *QueryComponent) GetChildren() []*QueryComponent {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *QueryComponent) GetComponentType() QueryComponent_ComponentType {
	if m != nil {
		return m.ComponentType
	}
	return QueryComponent_AND
}

func (m *QueryComponent) GetNot() *QueryComponent {
	if m != nil {
		return m.Not
	}
	return nil
}

func (m *QueryComponent) GetField() *Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type Field struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Value              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ComponentType        Field_ComponentType `protobuf:"varint,3,opt,name=component_type,json=componentType,proto3,enum=vinyl.Field_ComponentType" json:"component_type,omitempty"`
	Matches              *QueryComponent     `protobuf:"bytes,4,opt,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Field) GetComponentType() Field_ComponentType {
	if m != nil {
		return m.ComponentType
	}
	return Field_EQUALS
}

func (m *Field) GetMatches() *QueryComponent {
	if m != nil {
		return m.Matches
	}
	return nil
}

type Value struct {
	Double float64 `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	Float  float32 `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	Int32  int32   `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64  int64   `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	// uint32 not supported
	// uint64 not supported
	Sint32 int32 `protobuf:"zigzag32,6,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64 int64 `protobuf:"zigzag64,7,opt,name=sint64,proto3" json:"sint64,omitempty"`
	// fixed32 not supported
	// fixed64 not supported
	Bool                 bool            `protobuf:"varint,10,opt,name=bool,proto3" json:"bool,omitempty"`
	String_              string          `protobuf:"bytes,11,opt,name=string,proto3" json:"string,omitempty"`
	Bytes                []byte          `protobuf:"bytes,12,opt,name=bytes,proto3" json:"bytes,omitempty"`
	ValueType            Value_ValueType `protobuf:"varint,20,opt,name=value_type,json=valueType,proto3,enum=vinyl.Value_ValueType" json:"value_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{4}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetDouble() float64 {
	if m != nil {
		return m.Double
	}
	return 0
}

func (m *Value) GetFloat() float32 {
	if m != nil {
		return m.Float
	}
	return 0
}

func (m *Value) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *Value) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *Value) GetSint32() int32 {
	if m != nil {
		return m.Sint32
	}
	return 0
}

func (m *Value) GetSint64() int64 {
	if m != nil {
		return m.Sint64
	}
	return 0
}

func (m *Value) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *Value) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *Value) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Value) GetValueType() Value_ValueType {
	if m != nil {
		return m.ValueType
	}
	return Value_DOUBLE
}

type Insert struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insert) Reset()         { *m = Insert{} }
func (m *Insert) String() string { return proto.CompactTextString(m) }
func (*Insert) ProtoMessage()    {}
func (*Insert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{5}
}

func (m *Insert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insert.Unmarshal(m, b)
}
func (m *Insert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insert.Marshal(b, m, deterministic)
}
func (m *Insert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insert.Merge(m, src)
}
func (m *Insert) XXX_Size() int {
	return xxx_messageInfo_Insert.Size(m)
}
func (m *Insert) XXX_DiscardUnknown() {
	xxx_messageInfo_Insert.DiscardUnknown(m)
}

var xxx_messageInfo_Insert proto.InternalMessageInfo

func (m *Insert) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Insert) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Table struct {
	FieldOptions         map[string]*FieldOptions `protobuf:"bytes,1,rep,name=field_options,json=fieldOptions,proto3" json:"field_options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name                 string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{6}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetFieldOptions() map[string]*FieldOptions {
	if m != nil {
		return m.FieldOptions
	}
	return nil
}

func (m *Table) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// from record_metadata_options.proto
type FieldOptions struct {
	PrimaryKey           bool                      `protobuf:"varint,2,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Index                *FieldOptions_IndexOption `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{7}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetPrimaryKey() bool {
	if m != nil {
		return m.PrimaryKey
	}
	return false
}

func (m *FieldOptions) GetIndex() *FieldOptions_IndexOption {
	if m != nil {
		return m.Index
	}
	return nil
}

type FieldOptions_IndexOption struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Unique               bool     `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions_IndexOption) Reset()         { *m = FieldOptions_IndexOption{} }
func (m *FieldOptions_IndexOption) String() string { return proto.CompactTextString(m) }
func (*FieldOptions_IndexOption) ProtoMessage()    {}
func (*FieldOptions_IndexOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{7, 0}
}

func (m *FieldOptions_IndexOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions_IndexOption.Unmarshal(m, b)
}
func (m *FieldOptions_IndexOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions_IndexOption.Marshal(b, m, deterministic)
}
func (m *FieldOptions_IndexOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions_IndexOption.Merge(m, src)
}
func (m *FieldOptions_IndexOption) XXX_Size() int {
	return xxx_messageInfo_FieldOptions_IndexOption.Size(m)
}
func (m *FieldOptions_IndexOption) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions_IndexOption.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions_IndexOption proto.InternalMessageInfo

func (m *FieldOptions_IndexOption) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FieldOptions_IndexOption) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Records              [][]byte `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{8}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetRecords() [][]byte {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterEnum("vinyl.QueryComponent_ComponentType", QueryComponent_ComponentType_name, QueryComponent_ComponentType_value)
	proto.RegisterEnum("vinyl.Field_ComponentType", Field_ComponentType_name, Field_ComponentType_value)
	proto.RegisterEnum("vinyl.Value_ValueType", Value_ValueType_name, Value_ValueType_value)
	proto.RegisterType((*Request)(nil), "vinyl.Request")
	proto.RegisterType((*Query)(nil), "vinyl.Query")
	proto.RegisterType((*QueryComponent)(nil), "vinyl.QueryComponent")
	proto.RegisterType((*Field)(nil), "vinyl.Field")
	proto.RegisterType((*Value)(nil), "vinyl.Value")
	proto.RegisterType((*Insert)(nil), "vinyl.Insert")
	proto.RegisterType((*Table)(nil), "vinyl.Table")
	proto.RegisterMapType((map[string]*FieldOptions)(nil), "vinyl.Table.FieldOptionsEntry")
	proto.RegisterType((*FieldOptions)(nil), "vinyl.FieldOptions")
	proto.RegisterType((*FieldOptions_IndexOption)(nil), "vinyl.FieldOptions.IndexOption")
	proto.RegisterType((*Response)(nil), "vinyl.Response")
}

func init() { proto.RegisterFile("transport.proto", fileDescriptor_a97e32c760ec1b28) }

var fileDescriptor_a97e32c760ec1b28 = []byte{
	// 913 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0xa4, 0x48, 0xb6, 0x8f, 0xed, 0x74, 0xbb, 0x94, 0x8e, 0x26, 0x17, 0xd4, 0x23, 0x98,
	0xa9, 0x19, 0xa6, 0x66, 0x70, 0xdc, 0x0c, 0xf4, 0xce, 0x49, 0xd4, 0xd6, 0xe0, 0xda, 0x74, 0xad,
	0xc0, 0x94, 0x1b, 0x8f, 0x6c, 0xaf, 0xa9, 0xa6, 0x8a, 0xa4, 0xac, 0xd6, 0x01, 0x3d, 0x0e, 0x17,
	0xbc, 0x02, 0xb7, 0x3c, 0x19, 0x03, 0xb3, 0x67, 0x25, 0xa3, 0x40, 0xd3, 0x1b, 0xcf, 0xf9, 0xbe,
	0xf3, 0x69, 0x77, 0xcf, 0xaf, 0xe1, 0x9e, 0x14, 0x61, 0x92, 0x67, 0xa9, 0x90, 0x83, 0x4c, 0xa4,
	0x32, 0xa5, 0xf6, 0x4d, 0x94, 0x14, 0xb1, 0xf7, 0xb7, 0x01, 0x0d, 0xc6, 0xaf, 0x77, 0x3c, 0x97,
	0xf4, 0x18, 0x9a, 0xbb, 0x9c, 0x8b, 0x24, 0xbc, 0xe2, 0xae, 0xd1, 0x33, 0xfa, 0x2d, 0xb6, 0xc7,
	0xca, 0x97, 0x85, 0x79, 0xfe, 0x4b, 0x2a, 0x36, 0xae, 0xa9, 0x7d, 0x15, 0x56, 0xbe, 0x77, 0xbc,
	0xc8, 0xb3, 0x70, 0xcd, 0x5d, 0x4b, 0xfb, 0x2a, 0x4c, 0x1f, 0xc3, 0xbd, 0x6d, 0x14, 0xf3, 0xe5,
	0x86, 0xe7, 0x6b, 0x11, 0x65, 0x32, 0x15, 0xee, 0x61, 0xcf, 0xe8, 0x77, 0xd8, 0x91, 0xa2, 0x2f,
	0xf6, 0x2c, 0xfd, 0x0c, 0x1c, 0x19, 0xae, 0x62, 0x9e, 0xbb, 0x76, 0xcf, 0xea, 0xb7, 0x87, 0x9d,
	0x01, 0x3e, 0x70, 0x10, 0x28, 0x92, 0x95, 0x3e, 0xfa, 0x04, 0x20, 0x4a, 0x72, 0x2e, 0x64, 0x94,
	0x26, 0xb9, 0xeb, 0xa0, 0xb2, 0x5b, 0x2a, 0x27, 0xe8, 0x60, 0x35, 0x01, 0xf5, 0xc0, 0xbe, 0xde,
	0x71, 0x51, 0xb8, 0x8d, 0x9e, 0x51, 0x3b, 0xf3, 0xb5, 0xe2, 0x98, 0x76, 0x79, 0x3f, 0x82, 0x8d,
	0x98, 0x3e, 0x82, 0xb6, 0xe0, 0xeb, 0x54, 0x6c, 0x96, 0xb2, 0xc8, 0xaa, 0x0c, 0x80, 0xa6, 0x82,
	0x22, 0xe3, 0xf4, 0x09, 0x38, 0xdb, 0x28, 0x96, 0x5c, 0x60, 0x06, 0xda, 0xc3, 0x8f, 0xeb, 0xc7,
	0x9d, 0xa7, 0x57, 0x59, 0x9a, 0xf0, 0x44, 0xb2, 0x52, 0xe4, 0xfd, 0x69, 0xc2, 0xd1, 0x6d, 0x17,
	0xfd, 0x02, 0xec, 0xf5, 0xdb, 0x28, 0xde, 0xe0, 0xe1, 0x77, 0x1e, 0xa0, 0x35, 0xf4, 0x2b, 0x68,
	0xa2, 0x21, 0x78, 0xe2, 0x9a, 0x18, 0xe9, 0x1d, 0xfa, 0xbd, 0x8c, 0x7e, 0x0b, 0x47, 0xeb, 0x8a,
	0xd6, 0x51, 0xa8, 0x7a, 0x1c, 0x0d, 0x3f, 0x7d, 0xef, 0x87, 0x83, 0xbd, 0xa5, 0xc2, 0x63, 0xdd,
	0x75, 0x1d, 0xd2, 0xc7, 0x60, 0x25, 0xa9, 0xc4, 0x6a, 0xdd, 0x79, 0xb3, 0x52, 0xa8, 0x24, 0x6f,
	0x23, 0x1e, 0x6f, 0x5c, 0xfb, 0x56, 0x92, 0x9f, 0x2b, 0x8e, 0x69, 0x97, 0x37, 0x82, 0xee, 0xad,
	0xcb, 0x68, 0x03, 0xac, 0xf1, 0xec, 0x82, 0x1c, 0x50, 0x07, 0xcc, 0x39, 0x23, 0x86, 0x22, 0x66,
	0xf3, 0x80, 0x98, 0xb4, 0x05, 0xf6, 0xf3, 0x89, 0x3f, 0xbd, 0x20, 0x96, 0xf7, 0xbb, 0x09, 0x36,
	0x1e, 0x43, 0x29, 0x1c, 0xd6, 0xda, 0x12, 0x6d, 0x75, 0xef, 0x4d, 0x18, 0xef, 0x78, 0x59, 0x8d,
	0xea, 0xde, 0x1f, 0x14, 0xc7, 0xb4, 0x8b, 0x8e, 0xef, 0x48, 0xc8, 0x71, 0xfd, 0x91, 0x1f, 0xce,
	0xc3, 0x97, 0xd0, 0xb8, 0x0a, 0xe5, 0xfa, 0x2d, 0xcf, 0x3f, 0x9c, 0x8b, 0x4a, 0xe5, 0x65, 0xff,
	0x8d, 0x15, 0xc0, 0xf1, 0x5f, 0x5f, 0x8e, 0xa7, 0x0b, 0x72, 0x40, 0x09, 0x74, 0x5e, 0x30, 0x7f,
	0x1c, 0xf8, 0x6c, 0x19, 0xbc, 0x1c, 0xcf, 0x88, 0x41, 0xbb, 0xd0, 0x9a, 0xfa, 0x8b, 0x85, 0x86,
	0x18, 0xbe, 0xff, 0xea, 0xfb, 0xe0, 0x0d, 0xb1, 0x94, 0x67, 0x36, 0x0f, 0x96, 0x1a, 0x1e, 0xd2,
	0x36, 0x34, 0x26, 0x8b, 0xe5, 0xec, 0x72, 0x3a, 0x25, 0xb6, 0x02, 0xaf, 0xc6, 0xc1, 0xf9, 0x4b,
	0x7f, 0x41, 0x1c, 0xef, 0x2f, 0x13, 0x6c, 0x0c, 0x9b, 0x3e, 0x04, 0x67, 0x93, 0xee, 0x56, 0xb1,
	0xce, 0x94, 0xc1, 0x4a, 0x44, 0x1f, 0x80, 0xbd, 0x8d, 0xd3, 0x50, 0x62, 0xae, 0x4c, 0xa6, 0x81,
	0x62, 0xa3, 0x44, 0x9e, 0x0c, 0x31, 0x29, 0x36, 0xd3, 0xa0, 0x64, 0x4f, 0x47, 0x18, 0xae, 0xc5,
	0x34, 0x50, 0x27, 0xe7, 0x5a, 0xec, 0xf4, 0x8c, 0xfe, 0x7d, 0x56, 0xa2, 0x8a, 0x3f, 0x1d, 0xe1,
	0x8c, 0x51, 0x56, 0x22, 0x55, 0xb1, 0x55, 0x9a, 0xc6, 0x2e, 0xf4, 0x8c, 0x7e, 0x93, 0xa1, 0x8d,
	0x5a, 0x29, 0xa2, 0xe4, 0x67, 0xb7, 0x8d, 0x75, 0x2c, 0x91, 0xba, 0x71, 0x55, 0x48, 0x9e, 0xbb,
	0x1d, 0x5c, 0x0d, 0x1a, 0xd0, 0xa7, 0x00, 0x58, 0x44, 0x5d, 0xb7, 0x07, 0x58, 0xb7, 0x87, 0xf5,
	0x22, 0xeb, 0x5f, 0xac, 0x59, 0xeb, 0xa6, 0x32, 0xbd, 0x6b, 0x68, 0xed, 0x79, 0x95, 0xfa, 0x8b,
	0xf9, 0xe5, 0xd9, 0xd4, 0x27, 0x07, 0xd8, 0x58, 0xd3, 0xf9, 0x38, 0x20, 0x86, 0x32, 0x27, 0xb3,
	0xe0, 0x64, 0xa8, 0xf3, 0x3d, 0x99, 0x05, 0xa7, 0x23, 0x62, 0x29, 0xf1, 0x42, 0xd3, 0x76, 0x65,
	0x9f, 0x8e, 0x88, 0x43, 0x9b, 0x70, 0x78, 0x36, 0x9f, 0x4f, 0x49, 0x0b, 0xd9, 0x80, 0x4d, 0x66,
	0x2f, 0x08, 0xa8, 0x0f, 0xcf, 0xde, 0x04, 0xfe, 0x82, 0xb4, 0xbd, 0x21, 0x38, 0x7a, 0xf9, 0xa8,
	0x48, 0x70, 0x53, 0x95, 0x8d, 0xaa, 0x81, 0xca, 0xc5, 0x26, 0x94, 0x21, 0x26, 0xbf, 0xc3, 0xd0,
	0xf6, 0xfe, 0x30, 0xc0, 0xc6, 0xdd, 0x46, 0xcf, 0xa1, 0x8b, 0x43, 0xb2, 0x4c, 0x33, 0xbd, 0xd6,
	0x0c, 0x1c, 0xf6, 0x4f, 0xea, 0x0b, 0x50, 0x37, 0xea, 0x5c, 0x0b, 0xfc, 0x44, 0x8a, 0x82, 0x75,
	0xb6, 0x35, 0x6a, 0x3f, 0x20, 0xe6, 0xbf, 0x03, 0x72, 0x1c, 0xc0, 0xfd, 0xff, 0x7d, 0x46, 0x09,
	0x58, 0xef, 0x78, 0x51, 0xbe, 0x4f, 0x99, 0xf4, 0xf3, 0xdb, 0x73, 0xf4, 0x51, 0x7d, 0x34, 0xca,
	0x4f, 0xcb, 0x71, 0x7a, 0x66, 0x7e, 0x6d, 0x78, 0xbf, 0x19, 0xd0, 0xa9, 0xfb, 0xd4, 0xde, 0xcc,
	0x44, 0x74, 0x15, 0x8a, 0x62, 0xa9, 0x4e, 0x36, 0xb1, 0xe0, 0x50, 0x52, 0xdf, 0xf1, 0x82, 0x3e,
	0x55, 0x0d, 0xb5, 0xe1, 0xbf, 0x62, 0x9b, 0xb5, 0x87, 0x8f, 0xde, 0x73, 0xc1, 0x60, 0xa2, 0x04,
	0x1a, 0x30, 0xad, 0x3e, 0xfe, 0x06, 0xda, 0x35, 0x56, 0x45, 0x58, 0xdb, 0xcb, 0x68, 0xab, 0x86,
	0xda, 0x25, 0xd1, 0x75, 0xf9, 0xf6, 0x26, 0x2b, 0x91, 0xf7, 0x0c, 0x9a, 0x8c, 0xe7, 0x59, 0x9a,
	0xe4, 0xd8, 0xfa, 0x5c, 0x88, 0x54, 0x54, 0x25, 0x41, 0x40, 0x5d, 0x68, 0xe8, 0xcd, 0x9e, 0xe3,
	0x6e, 0xed, 0xb0, 0x0a, 0x9e, 0x51, 0xd0, 0x7f, 0x8d, 0x3f, 0xb5, 0xf6, 0x7f, 0x99, 0x2b, 0x07,
	0xff, 0x33, 0x4f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x54, 0x88, 0x6e, 0x93, 0x46, 0x07, 0x00,
	0x00,
}
