[package]
name = "fdb"
version = "0.1.0"
authors = ["maxmcd <max.t.mcdonnell@gmail.com>"]
edition = "2018"

[dependencies]
fdb_derive = { path = "../fdb_derive" }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.7", features = ["serde", "v4"] }
